.386
.MODEL     flat, stdCALL
OPTION     casemap :none




include \masm32\include\windows.inc   ; Includes
include \masm32\include\kernel32.inc
include \masm32\include\masm32.inc
include \masm32\include\masm32rt.inc 
includelib \masm32\lib\kernel32.lib
includelib \masm32\lib\masm32.lib


.DATA  
PRIMERNUMERO DB 1,0
SEGUNDONUMERO DB 1,0
COMPLEMENTO DB 1,0
COMPLEMENTO2 DB 1,0
INPUT1 DB 0,0
INPUT2 DB 0,0
MSMAYOR DB "ES MAYOR ",0
MSIGUAL DB "SON IGUALES",0
MSJ DB "INGRESE NUMERO",0
MSJSUMA DB "SUMA ",0
MSJRESTA DB "RESTA ",0
.DATA?
JK DB 50 DUP(?)

.CODE 
 
 
INICIO:
MAIN PROC
	INVOKE STDOUT, ADDR MSJ      ; IMPRIMIR MENSAJE
INVOKE STDOUT, ADDR INPUT1     ; PEDIR PRIMER NUMERO
	INVOKE STDIN, ADDR PRIMERNUMERO, 10
	INVOKE ATODW, ADDR PRIMERNUMERO	
	SUB PRIMERNUMERO,30H
INVOKE STDOUT, ADDR MSJ
INVOKE STDOUT, ADDR INPUT2     ; PEDIR SEGUNDO NUMERO
	INVOKE STDIN, ADDR SEGUNDONUMERO, 10
	INVOKE ATODW, ADDR SEGUNDONUMERO
	SUB SEGUNDONUMERO,30H
	XOR AX,AX
	XOR CL,CL
	MOV AL,PRIMERNUMERO
	MOV CL,SEGUNDONUMERO
	MOV COMPLEMENTO,AL
	MOV COMPLEMENTO2,CL
	MOV BL,COMPLEMENTO
	CMP BL,COMPLEMENTO2
	JE MISMONUMERO
	JG ESMAYOR
	JP ESMAYOR1
	
	
	
ESMAYOR1:
    ADD COMPLEMENTO2,30H
    INVOKE STDOUT, ADDR MSMAYOR
	INVOKE STDOUT, ADDR COMPLEMENTO2
	JMP DENUEVO
	
	
MISMONUMERO:
    INVOKE STDOUT, ADDR MSIGUAL
	JMP DENUEVO
	
	
ESMAYOR:
	ADD COMPLEMENTO, 30H
    INVOKE STDOUT, ADDR MSMAYOR
	INVOKE STDOUT, ADDR COMPLEMENTO
	JMP DENUEVO
	
	
FIN:
	INVOKE EXITPROCESS,0
	MAIN ENDP
	
	
DENUEVO:
	XOR AX,AX
	XOR CL,CL
	MOV AL,PRIMERNUMERO
	MOV CL,PRIMERNUMERO
	ADD AL,SEGUNDONUMERO
	SUB CL,SEGUNDONUMERO
	MOV PRIMERNUMERO,AL
	MOV SEGUNDONUMERO,CL
	ADD SEGUNDONUMERO,30H ;VALORESASCII
	ADD PRIMERNUMERO, 30H 
    INVOKE STDOUT, ADDR MSJSUMA
	INVOKE STDOUT, ADDR PRIMERNUMERO
    INVOKE STDOUT, ADDR MSJRESTA	
	INVOKE STDOUT, ADDR SEGUNDONUMERO
JMP FIN


END INICIO